Expose subtitle file size
morpheus65535/bazarr pull request #2252
Opened 2023-09-23 04:27 UTC by phyzical

Also adds an alias for the api under /v1

2023-09-23 04:29 UTC, phyzical commented on libs/flask_restx/api.py
> +           self._init_app(setup_state.app)
I had to make this change to a lib to allow creating an alias,

@morpheus65535 is this a file that can be modified or is it clobbered? 

If its clobbered any idea how we can make an alias of the api under `/api/v1` ?

2023-09-25 06:40 UTC, phyzical commented on bazarr/app/server.py
> +ui_bp.register_blueprint(api_bp, url_prefix='/api/v1', name="api_alias")
```suggestion
```

2023-09-25 06:40 UTC, phyzical commented on libs/flask_restx/api.py
> +
```suggestion
```

2023-09-25 06:41 UTC, phyzical commented
@morpheus65535 reverted the api change, i will see if i can make the required around a version lax application side 👍

2023-10-08 08:30 UTC, phyzical commented
@morpheus65535 anything still blocking this?

2023-10-08 11:40 UTC, morpheus65535 commented
> @morpheus65535 anything still blocking this?

Still one comment left

2023-10-10 01:50 UTC, morpheus65535 requested changes

2023-10-10 02:04 UTC, phyzical commented on bazarr/api/swaggerui.py
> +        "file_size": fields.Integer(),
```suggestion
        "file_size": fields.Integer()
```

2023-10-10 02:07 UTC, morpheus65535 approved these changes

2023-10-10 02:11 UTC, merged