Turn on Audio Sync for audio extraction process
morpheus65535/bazarr pull request #2648
Opened 2024-09-02 02:36 UTC by dvh312

# Problem description
- I used Whisper AI and recognized that the subtitles generated didn't have the correct timestamps, especially near the end of the video.

# Cause
1. The video files I'm using have some corrupted frames. 
2. ffmpeg try to "skip" these frames, causing the duration of the extracted audio to be significantly shorter than the original video duration.

# Solution
- Turning on audio sync to make the extracted audio matches the video timestamps.

# Screenshots

## Original command
```bash
ffmpeg  -i input.mp4  -acodec pcm_s16le -ac 1 -ar 16000 -f s16le output.wav 
```
[ffmpeg-before.log](https://github.com/user-attachments/files/16831254/ffmpeg-before.log)

Imported to Audacity, only shows the duration of 22m52s532ms. The video duration is 22m59s960ms. This means subtitles will be shifted by almost 7 seconds ahead.

<img width="1292" alt="Screenshot 2024-09-01 at 5 23 34 PM" src="https://github.com/user-attachments/assets/97a23497-c70a-4ea4-bd7f-5aa87306bf65">

<img width="1292" alt="Screenshot 2024-09-01 at 5 24 23 PM" src="https://github.com/user-attachments/assets/1a42c609-43e8-4f6b-ad29-2f0aea6620c5">

## Updated command
```bash
ffmpeg  -i input.mp4  -acodec pcm_s16le -ac 1 -ar 16000 -f s16le -af aresample=async=1 output.wav 
```

[ffmpeg-after.log](https://github.com/user-attachments/files/16831255/ffmpeg-after.log)

Audacity now shows the duration of 22m59s349ms, which is approximately the original video duration of 22m59s960ms

<img width="1292" alt="Screenshot 2024-09-01 at 5 28 37 PM" src="https://github.com/user-attachments/assets/88fee8d5-25a8-4a8b-9a62-164e809529d1">

2024-09-15 19:32 UTC, morpheus65535 requested changes
You can patch files in libs directory since they'll get overwritten when update update dependencies. You must find a way to do it from the provider itself or make a PR to ffprobe module itself, get it merged and we'll get it in next dependencies update cycle.

2024-09-15 19:55 UTC, anderson-oki commented
@dvh312 Morpheus means you **can't**, there is a typo.

2024-09-16 00:25 UTC, dvh312 commented
@morpheus65535 Thanks, let me find a way to do it in the provider.

2024-09-18 06:52 UTC, dvh312 commented
@morpheus65535 I've reverted the change in `libs`  and will made the update to ffsubsync directly.

2024-09-22 17:24 UTC, morpheus65535 approved these changes

2024-09-22 17:28 UTC, merged