Adds the option to skip mismatched fps to Titulky provider
morpheus65535/bazarr pull request #2677
Opened 2024-09-22 15:25 UTC by sambartik

Proof of concept. 

Do we really want such functionality? To get subtitles fps from the provider, it would cost an extra request per subtitle, but caching is utilized.

Untested.

2024-09-27 11:32 UTC, sambartik commented
Before I started working on this functionality I thought the FPS match was one of the matches the score calculation was based on, until I was proven wrong.

If the Skip mismatched FPS is not checked the extra request would not be justified at all. In the other case, it still would be just about borderline acceptable as there is no extra information to be gathered that has any significance to bazarr.

Have we considered adding an FPS match to providers such that it weighs in the score calculation?

2024-09-30 13:45 UTC, morpheus65535 requested changes

2024-09-30 13:45 UTC, morpheus65535 commented on custom_libs/subliminal_patch/providers/titulky.py
> +            raise ConfigurationError(f"Approved_only {approved_only} must be a boolean!")
cut and paste issue here

2024-10-01 18:42 UTC, sambartik commented
> FPS isn't returned for most provider so I'm not sure there's a benefit of doing this globally in the score system. I suppose we can keep it in this provider but exclude from results those where the fps doesn't matches.

I don't understand what you meant by excluding from results. Could you please elaborate?

The behaviour as of this PR is that when the "Skip wrong FPS" checkbox in the provider settings is checked, it effectively skips those subtitles by having an empty match set.

2024-10-01 19:53 UTC, morpheus65535 commented
> I don't understand what you meant by excluding from results. Could you please elaborate?
> 
> 
> 
> The behaviour as of this PR is that when the "Skip wrong FPS" checkbox in the provider settings is checked, it effectively skips those subtitles by having an empty match set.

This is exactly what I meant. 😄

2024-10-01 19:55 UTC, morpheus65535 commented
Would it be a good idea to do the additional request only if skip wrong fps is enabled?

2024-10-01 20:26 UTC, sambartik commented
I think yes. That makes more sense since when the checkbox is disabled it only logs the fact the FPS were mismatched, which brings little value for an additional request.

FPS value of each subtitle is cached based on its ID, which minimizes the load. So when a user searches for the same episode/movie only the first search request would result in an additional request. That brings me the question - how long does the cache persist?

2024-10-03 01:42 UTC, morpheus65535 approved these changes

2024-10-03 01:56 UTC, morpheus65535 commented
> That brings me the question - how long does the cache persist?

If not configured, it's 30 days.

2024-10-08 23:38 UTC, merged