Napiprojekt provider new options:
morpheus65535/bazarr pull request #2752
Opened 2024-11-09 21:15 UTC by destpstrzy

Napiprojekt is big polish subtitle base but there are a lot of AI generated subtitles uploaded by random people. I have done some improvements that should eliminate limit incorrect downloads:

Napiprojekt provider new options:
- Info about releases
- Skip subtitles without authors or possibly AI generated
- Download subtitles with real name authors only

2024-11-12 01:46 UTC, morpheus65535 commented
Could you rebase this PR on development branch please?

https://github.com/morpheus65535/bazarr/blob/master/CONTRIBUTING.md#community-devs

2024-11-13 10:37 UTC, destpstrzy commented
> Could you rebase this PR on development branch please?
> 
> https://github.com/morpheus65535/bazarr/blob/master/CONTRIBUTING.md#community-devs

Done. Sorry for the mistake.

2024-11-18 04:11 UTC, morpheus65535 requested changes

2024-11-18 04:11 UTC, morpheus65535 commented on frontend/package-lock.json
Don't bring this with you please.

2024-11-18 04:11 UTC, morpheus65535 commented on frontend/package.json
Don't bring this with you please.

2024-11-18 04:11 UTC, morpheus65535 commented on changelog-master.hbs
Don't bring this with you please.

2024-11-18 04:11 UTC, morpheus65535 commented on changelog-dev.hbs
Don't bring this with you please.

2024-11-25 04:29 UTC, morpheus65535 approved these changes

2024-11-25 04:33 UTC, merged